// JavaScript Document
function $(id){return (typeof id == "string" ? document.getElementById(id) : id);};var lastInput;var selectedIndex=-1;function getData(source){var xmlHttp=false;if(window.XMLHttpRequest){xmlHttp=new XMLHttpRequest();}else if(window.ActiveXObject){xmlHttp=new ActiveXObject("Microsoft.XMLHTTP");};if(xmlHttp){xmlHttp.open("GET",source);xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState==4&&xmlHttp.status==200){var message=xmlHttp.responseText;var rData=eval("new Array("+message+");");if(rData.length>1){var callBack=Suggest_apply(frameElement,"Ajax",rData,new Array(""));eval(callBack);}else{ "closefun();"};selectedIndex=-1;}};xmlHttp.send(null);}};function connectSoSuggest(){var input=document.current_wd;if(input.value){if(escape(input.value)!=lastInput){lastInput=escape(input.value);	getData(document.ajax_Url+"&wd="+escape(input.value));}}else{"closefun();"}};function Suggest_apply(unusedVariable,searchWord,results,unusedArray){document.current_wd_list.className="div_word_show";var data="";for(var i=0;i<results.length;i+=2){data+="<div onmouseout=\"this.className=''\" onmouseover=\"document.current_wd_click=false;document.current_wd.value='"+results[i]+"';this.className='div_word_selected'\" onclick=\"document.current_wd_click=false;closefun();return false;\"  ><span style=\"display:none;\">"+results[i]+"</span><span>"+results[i+1]+"</span>"+results[i]+"</div>";};document.current_wd_list.innerHTML=data;};function checkKeyCode(event,wd_id,ajax_url){document.ajax_Url=ajax_url;document.current_wd_click=false;document.current_wd=wd_id;document.current_wd_list=wd_id.nextSibling;var keyCode=event.keyCode;if(keyCode==40||keyCode==38){var isUp=false;if(keyCode==40)isUp=true;chageSelection(isUp);}else if(keyCode==13){closefun();}else{connectSoSuggest();}};

function connectSoSuggest_click(){var input=document.current_wd;if(input.value){lastInput=escape(input.value);};	getData(document.ajax_Url+"&wd="+escape(input.value));};

function checkKeyCode_click(wd_id,ajax_url){document.ajax_Url=ajax_url;document.current_wd_click=true;document.current_wd=wd_id;document.current_wd_list=wd_id.nextSibling;connectSoSuggest_click();};

function chageSelection(isUp){var objouter=document.current_wd_list;var obj_wd=document.current_wd;if(objouter.className=='div_word_hidden'){objouter.style.display='none';}else{objouter.className="div_word_show";if(isUp){selectedIndex=selectedIndex+1;}else{selectedIndex=selectedIndex-1;}};var maxIndex=objouter.childNodes.length-1;if(selectedIndex<0){selectedIndex=maxIndex};if(selectedIndex>maxIndex){selectedIndex=0};for(intTmp=0;intTmp<=maxIndex;intTmp++){if(intTmp==selectedIndex){objouter.childNodes[intTmp].className="div_word_selected";var nowDiv=objouter.childNodes[intTmp].innerHTML;if(nowDiv!='undefined')obj_wd.value=objouter.childNodes[intTmp].childNodes[0].innerHTML;}else{objouter.childNodes[intTmp].className="";}}} 
function closefun(){if(document.current_wd_click) return true;try{ document.current_wd_list.className = 'div_word_hidden';document.current_wd_list.innerHTML= '';}catch(e){}}; 
try{ if(document.all){document.attachEvent('onclick',closefun);}else{document.addEventListener('click',closefun,true);}}catch(e){}
document.current_wd_click=false;document.current_wd=null;document.current_wd_list=null;document.ajax_Url=null;